"""
Tearsheet — production-style performance report generator.

Renders a self-contained HTML tearsheet (equity curve, drawdown chart,
rolling Sharpe, weights, and a metrics table) from a BacktestResult, using
matplotlib for charts (base64-embedded, so the HTML is fully portable —
no external files, safe to email or drop in a deal room).
"""
from __future__ import annotations
import io
import base64
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


class Tearsheet:
    def __init__(self, backtest_result, strategy_name: str = "Portfolio Strategy"):
        self.result = backtest_result
        self.name = strategy_name

    @staticmethod
    def _fig_to_base64(fig) -> str:
        buf = io.BytesIO()
        fig.savefig(buf, format="png", dpi=130, bbox_inches="tight")
        plt.close(fig)
        buf.seek(0)
        return base64.b64encode(buf.read()).decode("utf-8")

    def _equity_chart(self) -> str:
        fig, ax = plt.subplots(figsize=(9, 3.2))
        self.result.equity_curve.plot(ax=ax, color="#1f6f5c", linewidth=1.6)
        ax.set_title("Cumulative Growth of $1")
        ax.set_ylabel("Portfolio Value")
        ax.grid(alpha=0.25)
        return self._fig_to_base64(fig)

    def _drawdown_chart(self) -> str:
        eq = self.result.equity_curve
        dd = eq / eq.cummax() - 1
        fig, ax = plt.subplots(figsize=(9, 2.4))
        ax.fill_between(dd.index, dd.values, 0, color="#b23b3b", alpha=0.5)
        ax.set_title("Drawdown")
        ax.grid(alpha=0.25)
        return self._fig_to_base64(fig)

    def _rolling_sharpe_chart(self, window: int = 63) -> str:
        r = self.result.returns
        roll_sharpe = (r.rolling(window).mean() / r.rolling(window).std()) * (252 ** 0.5)
        fig, ax = plt.subplots(figsize=(9, 2.4))
        roll_sharpe.plot(ax=ax, color="#2f5aa8", linewidth=1.3)
        ax.axhline(0, color="black", linewidth=0.7)
        ax.set_title(f"Rolling {window}-Day Sharpe")
        ax.grid(alpha=0.25)
        return self._fig_to_base64(fig)

    def _weights_chart(self) -> str:
        w = self.result.weights_history
        fig, ax = plt.subplots(figsize=(9, 3.2))
        w.plot.area(ax=ax, linewidth=0, cmap="tab20")
        ax.set_title("Weight Allocation Over Time")
        ax.legend(loc="upper left", bbox_to_anchor=(1.0, 1.0), fontsize=7)
        ax.set_ylim(0, 1)
        return self._fig_to_base64(fig)

    def _metrics_table_html(self) -> str:
        m = self.result.metrics
        pretty = {
            "annualized_return": ("Annualized Return", "{:.2%}"),
            "annualized_volatility": ("Annualized Volatility", "{:.2%}"),
            "sharpe_ratio": ("Sharpe Ratio", "{:.2f}"),
            "sortino_ratio": ("Sortino Ratio", "{:.2f}"),
            "max_drawdown": ("Max Drawdown", "{:.2%}"),
            "calmar_ratio": ("Calmar Ratio", "{:.2f}"),
            "var_95": ("VaR (95%, daily)", "{:.2%}"),
            "cvar_95": ("CVaR (95%, daily)", "{:.2%}"),
            "avg_rebalance_turnover": ("Avg Turnover / Rebalance", "{:.2%}"),
            "n_periods": ("Periods", "{:.0f}"),
        }
        rows = ""
        for key, (label, fmt) in pretty.items():
            if key in m:
                rows += f"<tr><td>{label}</td><td>{fmt.format(m[key])}</td></tr>"
        return f"<table class='metrics'>{rows}</table>"

    def to_html(self, path: str) -> str:
        equity_b64 = self._equity_chart()
        dd_b64 = self._drawdown_chart()
        sharpe_b64 = self._rolling_sharpe_chart()
        weights_b64 = self._weights_chart()
        metrics_html = self._metrics_table_html()

        html = f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{self.name} — Tearsheet</title>
<style>
  body {{ font-family: -apple-system, 'Segoe UI', Roboto, sans-serif; background:#f7f7f5; color:#1a1a1a; margin:0; padding:32px; }}
  .container {{ max-width: 980px; margin: 0 auto; }}
  h1 {{ font-size: 22px; margin-bottom: 4px; }}
  .subtitle {{ color:#666; margin-bottom: 28px; font-size: 13px; }}
  .card {{ background:white; border-radius:10px; padding:20px 24px; margin-bottom:20px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }}
  img {{ width:100%; height:auto; display:block; }}
  table.metrics {{ border-collapse: collapse; width: 100%; }}
  table.metrics td {{ padding: 8px 10px; border-bottom: 1px solid #eee; font-size: 14px; }}
  table.metrics tr td:first-child {{ color:#555; }}
  table.metrics tr td:last-child {{ text-align:right; font-weight:600; }}
</style>
</head>
<body>
<div class="container">
  <h1>{self.name}</h1>
  <div class="subtitle">Walk-forward backtest tearsheet — generated by Portfolio Optimizer</div>

  <div class="card"><h3>Performance Summary</h3>{metrics_html}</div>
  <div class="card"><img src="data:image/png;base64,{equity_b64}"/></div>
  <div class="card"><img src="data:image/png;base64,{dd_b64}"/></div>
  <div class="card"><img src="data:image/png;base64,{sharpe_b64}"/></div>
  <div class="card"><img src="data:image/png;base64,{weights_b64}"/></div>
</div>
</body>
</html>
"""
        with open(path, "w") as f:
            f.write(html)
        return path
